"""
Library:     test_import_and_reset.py
Jurisdiction: ["PYTHON", "CORE_COMMAND"]
Status:      OFFICIAL — Core-Command/Lib (v1.1)
Author:      Elton Boehnen
Version:     1.1 (OFFICIAL)
Date:        2026-04-23
Description: Core-Command library component.
"""
import os
import sys
import shutilSCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
LIB_DIR = os.path.dirname(SCRIPT_DIR)
BASE_DIR = os.path.dirname(LIB_DIR)

if LIB_DIR not in sys.path:
    sys.path.insert(0, LIB_DIR)

from BEJSON_CMS_Lib import CMSDatabase

MASTER_DB = os.path.join(BASE_DIR, "Data", "BEJSON_WEB_BUILDER", "site_master.json")

def test():
    print("--- Import & Reset Test ---")
    cms = CMSDatabase(MASTER_DB)
    
    # 1. Create a dummy HTML file with Word-like artefacts
    dummy_html = os.path.join(BASE_DIR, "test_import.html")
    with open(dummy_html, "w") as f:
        f.write("""
        <html>
            <head><title>Test Word Import</title></head>
            <body>
                <div class="MsoNormal">
                    <p class="MsoNormal" style="mso-margin-top-alt:auto;">This is a test paragraph with <o:p>Word tags</o:p>.</p>
                    <p>Generated by Microsoft Word</p>
                </div>
            </body>
        </html>
        """)
    
    # 2. Test Import
    print("\n[1] Importing HTML file...")
    uuid = cms.import_html_file(dummy_html, category="News", author="Importer")
    if uuid:
        print(f"Import Successful! UUID: {uuid}")
        content = cms.get_page_content(uuid)
        print(f"Cleaned HTML: {content['html']}")
    else:
        print("Import Failed")
        
    # 3. Test Factory Reset
    print("\n[2] Performing Factory Reset...")
    if cms.factory_reset(confirm=True):
        print("Reset Successful!")
        pages = cms.list_pages()
        print(f"Pages after reset: {len(pages)}")
    else:
        print("Reset Failed")

    # Cleanup
    if os.path.exists(dummy_html):
        os.remove(dummy_html)

    print("\n--- Test Complete ---")

if __name__ == "__main__":
    test()
