"""
Library:     lib_html2_toothpaste.py
Jurisdiction: ["PYTHON", "CORE_COMMAND"]
Status:      OFFICIAL — Core-Command/Lib (v1.1)
Author:      Elton Boehnen
Version:     1.1 (OFFICIAL)
Date:        2026-04-23
Description: "Toothpaste" fresh style body template for BEJSON HTML generation.
             Features a clean, airy aesthetic with minty accents and rounded corners.
"""
import html as html_mod

# ═══════════════════════════════════════════════════════
# TOOTHPASTE THEME VARIABLES
# ═══════════════════════════════════════════════════════

TOOTHPASTE_CSS = """
    :root {
        --tp-bg: #f8fcfd;
        --tp-surface: #ffffff;
        --tp-primary: #00b4d8;
        --tp-secondary: #90e0ef;
        --tp-accent: #caf0f8;
        --tp-text: #2b2d42;
        --tp-text-dim: #8d99ae;
        --tp-border: #edf2f4;
        --tp-radius: 12px;
        --tp-shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.05), 0 2px 4px -1px rgba(0, 0, 0, 0.03);
    }
    
    body.toothpaste {
        background-color: var(--tp-bg);
        color: var(--tp-text);
        font-family: 'Inter', -apple-system, sans-serif;
        line-height: 1.6;
        margin: 0;
        padding: 40px 20px;
    }
    
    .tp-container {
        max-width: 900px;
        margin: 0 auto;
        background: var(--tp-surface);
        padding: 40px;
        border-radius: var(--tp-radius);
        border: 1px solid var(--tp-border);
        box-shadow: var(--tp-shadow);
    }
    
    .tp-header {
        border-bottom: 3px solid var(--tp-primary);
        padding-bottom: 20px;
        margin-bottom: 30px;
    }
    
    .tp-header h1 {
        margin: 0;
        color: var(--tp-primary);
        font-weight: 800;
        letter-spacing: -0.02em;
    }
    
    .tp-card {
        background: var(--tp-accent);
        padding: 20px;
        border-radius: var(--tp-radius);
        margin-bottom: 20px;
        border: 1px solid var(--tp-secondary);
    }
    
    .tp-btn {
        display: inline-block;
        padding: 10px 24px;
        background: var(--tp-primary);
        color: white;
        text-decoration: none;
        border-radius: 30px;
        font-weight: 600;
        transition: transform 0.2s ease;
    }
    
    .tp-btn:hover {
        transform: translateY(-2px);
        background: #0096c7;
    }
"""

def html_toothpaste_page(title, body, meta=""):
    """Generate a complete HTML page with the Toothpaste theme."""
    return f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{html_mod.escape(title)}</title>
    <style>
        @import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;600;800&display=swap');
        {TOOTHPASTE_CSS}
    </style>
</head>
<body class="toothpaste">
    <div class="tp-container">
        <header class="tp-header">
            <h1>{html_mod.escape(title)}</h1>
            <div style="font-size: 0.85rem; color: var(--tp-text-dim); margin-top: 5px;">{meta}</div>
        </header>
        <div class="tp-content">
            {body}
        </div>
        <footer style="margin-top: 60px; text-align: center; color: var(--tp-text-dim); font-size: 0.8rem;">
            Generated by lib_html2_toothpaste.py · Fresh & Clean
        </footer>
    </div>
</body>
</html>"""
